In [1]:
import numpy as np

In [8]:
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0, 0, 0, 1]]).T

In [17]:
def sig(z):
    return 1 / (1 + (np.exp(-z)))

In [ ]:
def derivativeSig(z):
    return sig(z) * (1 - sig(z))

In [12]:
# no hidden layer weights
weights = 2 * np.random.random((2, 1)) - 1
bias = 2 * np.random.random(1) - 1
weights, bias

(array([[-0.60766414],
        [ 0.58374327]]), array([-0.72379202]))

In [13]:
# forward propagation without any hidden layer
output0 = X
output = sig(np.dot(output0, weights) + bias)
output

array([[ 0.3265585 ],
       [ 0.46504493],
       [ 0.2089186 ],
       [ 0.32131985]])

In [15]:
wh = 2 * np.random.random((2, 2)) - 1
bh = 2 * np.random.random((1, 2)) - 1
wo = 2 * np.random.random((2, 1)) - 1
bo = 2 * np.random.random((1, 1)) - 1

In [16]:
output0 = X
outputHidden = sig(np.dot(output0, wh) + bh)
output = sig(np.dot(outputHidden, wo) + bo)
output

array([[ 0.54635649],
       [ 0.50899046],
       [ 0.53448421],
       [ 0.50801058]])